### PR TITLE
Bundle code + other contributors

### PR DESCRIPTION
**Pull request by peterdesmet**
This PR started because I noticed a typo in "alph**e**betical" and because it was mentioned twice. This is corrected in 9f1e739

But then I looked at the list of contributors again, and thought: why not bundle them together? This is done in 37966b9. See [here](https://github.com/ropensci/rgbif/blob/37966b9c3a51954c6e3443131960ef3e4167ebd6/README.md#contributors) how it looks like.

1. Easier to maintain (just one list)
1. Simpler title and intro
1. Code contributors are considered normal contributors, but listed in bold
1. Only used github user names (easier to maintain)
1. Considerable code contributors could be listed with their name + ORCID in the authors anyway

Regarding 5:

- benmarwick, jarioksa, johnbaums, SriramRamesh, steven2249 are not listed in the authors
- JanLauGe (?) is listed in the authors, but not in the contributors

I didn't generate the website (yet).

### CODE REVIEW

**Comment by sckott** [comment]
thanks @peterdesmet !  LGTM 

thinking about it - maybe it should be scripted. I don't think we want that to run any time someone runs the readme.rmd b/c of pain with/without Github PAT, but maybe in a separate script in `inst/ignore`, and a note in readme.rmd to run that from time to time. Will do that after merge

**Comment by sckott** [comment]
for 5: being listed in authors in DESCRIPTION file is sort of a fuzzy manual step. but looks like all contributors of any code are in the list in README, yes?

**Comment by peterdesmet** [comment]
> but looks like all contributors of any code are in the list in README, yes?

One was not bolded, fixed in b86db0f

> maybe it should be scripted... Will do that after merge

Cool. Seems like a useful function for any package.

**Comment by sckott** [comment]
thanks

**Pull request merged**
