### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by steven2249**
add codecov badge

### CODE REVIEW

**Comment by sckott** [comment]
HI @steven2249 can you please add to both of the readme files

**Comment by sckott** [comment]
goes for all similar changes in other pkgs

**Comment by steven2249** [comment]
Sure. I think I've already add to both readme.rmd and md.

**Comment by sckott** [comment]
Oh, please do those in the same Pull request - you can cancel this one and add it to the previous one, just commit to the same branch and it will be added

**Pull request closed without merging**
