### PR TITLE
Install Instructions for mac users

### PR DESCRIPTION
**Pull request by SriramRamesh**
#254

### CODE REVIEW

**Comment by sckott** [comment]
@SriramRamesh thanks

@mdsumner  what's the best practice for installing `gdal` on OSX nowdays? I haven't really kept up with that. Just a `brew install gdal` ?

**Comment by mdsumner** [comment]
No idea sorry, not a mac user, how about this though? 

https://github.com/edzer/sfr/blob/master/README.md#macos

**Comment by sckott** [comment]
thanks @mdsumner - sorry i assumed that. that looks good to me. 

@SriramRamesh for `gdal`, just link to that readme - and can keep other install things the same

**Comment by SriramRamesh** [comment]
Hi, I added the link....

**Comment by sckott** [comment]
thanks

**Pull request merged**
